@ECHO OFF
REM === DO NOT EDIT THIS FILE ===
REM Run this script to upload a NuGet package to the NuGet gallery.
REM When you run this script it will prompt you for a NuGet package file (.nupkg) and then upload it to the NuGet gallery.
REM The project's .nupkg file should be in the same directory as the project's .dll/.exe file (typically bin\Debug or bin\Release).
REM You may edit the Config.ps1 file to adjust the settings used to upload the package to the NuGet gallery.
REM To run this script from within Visual Studio, right-click on this file from the Solution Explorer and choose Run.
SET THIS_SCRIPTS_DIRECTORY=%~dp0
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.Emailer\Koden.Utils.Emailer.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.Logger\Koden.Utils.Logger.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.AD\Koden.Utils.AD.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.Encryption\Koden.Utils.Encryption.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.MVC\Koden.Utils.MVC.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.IO\Koden.Utils.IO.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.FTP\Koden.Utils.FTP.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.Exchange\Koden.Utils.Exchange.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.REST\Koden.Utils.REST.csproj\""
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "%THIS_SCRIPTS_DIRECTORY%DoNotModify\UploadNuGetPackage.ps1 -ProjectFilePath \"..\Koden.Utils.SharePoint\Koden.Utils.SharePoint.csproj\""

pause